controller:
  config:
    worker-processes: "auto"
    allow-snippet-annotations: "true"

  ingressClassResource:
    default: true
  
  extraEnvs:
    - name: TZ
      value: Asia/Tehran

  kind: DaemonSet
  priorityClassName: "system-cluster-critical"

  # replicaCount: 1
  hostPort:
    enabled: true

  service:
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443
 
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
