apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
  labels:
    ping: pong 
spec:
  initContainers:
  - name: init1
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ["sleep", "1"]
  - name: init2
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ["sleep", "1"]
  containers:
  - name: busybox
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ["sleep", "3600"]
  - name: b2
    image: busybox
    imagePullPolicy: Always
    command: ["sleep", "3600"]
  - name: b3
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ["sleep", "3600"]
  terminationGracePeriodSeconds: 1